[build-system]
requires = ["setuptools >= 64", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "bluepyemodel"
authors = [
    {name = "Blue Brain Project, EPFL"},
]
description="Blue Brain Python Electrical Modeling Pipeline"
readme = "README.rst"
license = {file = "LICENSE.txt"}
requires-python = ">= 3.11"
dynamic = ["version"]
dependencies = [
    "numpy",
    "fasteners>=0.16",
]
keywords=[
    "computational neuroscience",
    "simulation",
    "analysis",
    "parameters",
    "Blue Brain Project",
]
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX",
    "Topic :: Scientific/Engineering",
    "Programming Language :: Python :: 3",
    "Topic :: Utilities",
]

[project.optional-dependencies]
extraction = [
    "bluepyefe>=2.3.48",
    "efel>=5.5.5",
    "scipy>=1.16.1",
]
optimisation = [
    "bluepyopt>=1.14.10",
    "bluepyefe>=2.3.48",
    "neuron>=8.0",
    "efel>=5.5.5",
    "scipy>=1.16.1",
    "neurom>=3.0",
    "morph_tool>=2.8",
    "morphio",
]
validation = [
    "bluepyopt>=1.14.10",
    "neuron>=8.0",
    "efel>=5.5.5",
    "scipy>=1.16.1",
    "neurom>=3.0",
    "morph_tool>=2.8",
    "morphio",
    "matplotlib",
    "bluepyefe>=2.3.48",
    "currentscape>=0.0.11",
]
export = [
    "bluepyopt>=1.14.10",
    "bluepyefe>=2.3.48",
    "neuron>=8.0",
    "efel>=5.5.5",
    "h5py",
    "jinja2>=3.0.3",
    "neurom>=3.0",
    "morph_tool>=2.8",
    "morphio",
]
parallel = [
    "ipyparallel>=6.3",
]
luigi = [
    "luigi>=3.7.2",
    "luigi-tools>=0.0.12",
]
nexus = [
    "nexusforge>=0.8.2",
    "entity_management>=1.2",
    "pyJWT>=2.1.0",
    "pandas",
]
docs = [
    "graphviz",
    "sphinx<9",
    "sphinx-bluebrain-theme",
    "luigi>=3.7.2",
    "luigi-tools>=0.0.12",
]
test = [
    "pytest>=6.2",
    "dictdiffer>=0.8",
]
all = [
    "bluepyemodel[local,parallel,luigi,nexus,test]",
]
local = [
    "bluepyemodel[extraction,optimisation,validation,export]",
]

[project.urls]
Homepage = "https://github.com/openbraininstitute/BluePyEModel"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
exclude = ["tests",]

[tool.setuptools_scm]
version_scheme = "python-simplified-semver"
local_scheme = "no-local-version"
